# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
matrix:
  include:
    - python: '3.6'
      env:
        - TOXARGS="-e py36"
          MYTARDIS=false
    - python: '2.7'
      env:
        - TOXARGS="-e py27,mytardis"
          MYTARDIS=true


# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox-travis

before_script:
  - wget https://github.com/mytardis/mytardis/archive/develop.tar.gz -O /tmp/mytardis.tar.gz
  - tar -xvf /tmp/mytardis.tar.gz
  - export MYTARDISPATH=$PWD/mytardis

# command to run tests, e.g. python setup.py test
script:
  - tox $TOXARGS


